% TMS_bfield_calc.m
%
% Goodwin, Brian 2012-03-08
%
% We know that this file contains correct information about the magnetic
% field generated by a single current dipole because it has been tested
% with 2 different equations, both equations have little error between
% them. The first equation calculates the B field (bf) indirectly by
% calculating the magnetic vector potential (A). The second equation
% calculates the B field (B) directly from the current dipole.
%
% a_field_newcoil.m

clear
clc

% Magnetic permeability of free space
mu_0=4*pi*1E-7; % [N/A^2] = [H/m] = [J/(A^2m)]

disp 'TMS Coil Creation'
tic
%% Coil Parameters:
%
% Salinas et al. (2007) notes that the height of the coil windings is one
% of the more important parameters when estimating the magnetic field in
% close proximity of the coil.

h = 7.25; % [mm] (Salinas et al., 2007)
ID1 = 28.36*2; % [mm] Inner diameter (Salinas et al.,2007)
ID2 = 28.11*2; % [mm] (Salinas et al.,2007)
OD1 = 44.98*2; % [mm] Outer diameter (Salinas et al.,2007)
OD2 = 44.43*2; % [mm] (Salinas et al.,2007)

% Center of Coil(s)
c1=[-46.63,0,0]*1e-3; % [m] (Salinas et al.,2007)
c2=[47.11,0,0]*1e-3; % [m] (Salinas et al.,2007)

turns = 9;
L = 15.5; % [uH]
PeakMagneticField = 2.2; % [T]
PeakElectricField = 660; % [V/m]
PeakCurrent = 8e3; % [A]

% Magnetic permeability of free space
mu_0=4*pi*1E-7; % [N/A^2] = [H/m] = [J/(A^2m)]
mu_r=1; % Relative permeability

%% Current Dipole Coil Approximation
% Number of approximate current dipoles per coil
nh=5; % current dipoles along the height of the wires.
n=80; % number of current dipoles per turn per height
theta=linspace(0,2*pi-2*pi/n,n);
qDirCalc=[cos(theta);sin(theta);zeros(1,n)];
k=[zeros(2,n);ones(1,n)]; % [0,0,1] vector for the "for" loop below.

% Multiturn coil approximation
D1=linspace(ID1,OD1,turns)*1e-3; % (1x9) conversion from [mm] to [m]
D2=linspace(ID2,OD2,turns)*1e-3; % (1x9) conversion from [mm] to [m]
Q1=PeakCurrent*pi*D1/n/nh; % (1x9) [Am] strength of approximate current dipole
Q2=PeakCurrent*pi*D2/n/nh; % (1x9) [Am] strength of approximate current dipole

% Q direction vectors with unit magnitude.
Qdir1=cross(qDirCalc,k); % (3 x n)
Qdir2=cross(qDirCalc,-k); % (3 x n)
Q1=reshape(repmat(reshape(repmat(Q1,3,1),turns*3,1),1,n)',3,n*turns);
Q2=reshape(repmat(reshape(repmat(Q2,3,1),turns*3,1),1,n)',3,n*turns);

Qcoil1=repmat(Qdir1,1,turns).*Q1; % [Am] Magnitude applied to dipoles.
Qcoil2=repmat(Qdir2,1,turns).*Q2; % [Am] Magnitude applied to dipoles.

locarray1=repmat(c1',1,n);
locarray2=repmat(c2',1,n);

qloc1=repmat(locarray1,1,turns)+...
    reshape(repmat(reshape(repmat(D1/2,3,1),turns*3,1),1,n)',3,n*turns).*repmat(qDirCalc,1,turns); % [m]
qloc2=repmat(locarray2,1,turns)+...
    reshape(repmat(reshape(repmat(D2/2,3,1),turns*3,1),1,n)',3,n*turns).*repmat(qDirCalc,1,turns); % [m]

temp1=qloc1;
temp2=qloc2;
qloc1=[];
qloc2=[];

for zloc=linspace(0,h*1e-3,nh)
    qloc1=[qloc1,temp1+[zeros(2,n*turns);ones(1,n*turns)*zloc]];
    qloc2=[qloc2,temp2+[zeros(2,n*turns);ones(1,n*turns)*zloc]];
end
Qcoil1=repmat(Qcoil1,1,nh);
Qcoil2=repmat(Qcoil2,1,nh);

qloc=[qloc1,qloc2];
Q=[Qcoil1,Qcoil2];

% % Write coil to file for SCIRun
% fid=fopen('coil.pts','w');
% fprintf(fid,'%8.8f %8.8f %8.8f\n',qloc);
% fclose(fid);
% fid=fopen('coil.txt','w');
% fprintf(fid,'%8.8f %8.8f %8.8f\n',Q);
% fclose(fid);


